'''
Created on 15 Mar 2017

@author: Comma
'''


class Stages(object):
    '''
    Bot Stage
    '''

    MAIN_PANEL = 1
    CHOOSING = 2
    TICKET_CONDITION = 3
    TICKET_CONDITION_REPLY = 4
    POST_CONDITION = 5
    POST_CONDITION_REPLY = 6
    SUBMIT_TICKET = 7
    CHECK_MY_TICKET = 8
    UPDATE_TICKET = 9
    UPDATE_TICKET_REPLY = 10
    UPDATE_TICKET_SUBMIT = 11
    CONTACT_SELL = 12
    CONTACT_SELL_REPLY = 13
    PAIR_UP_START = 14
    PAIR_UP_MESSAGE = 15
    PAIR_UP_MESSAGE_SEND = 16
    PAIR_UP_MESSAGE_RECEIVE = 17
    SUPPORT_EVENT_START = 18
    SUPPORT_EVENT_INFO = 19
    SUPPORT_EVENT_END = 20

    ADMIN_START = 51
    ADMIN_CHOICE = 52
    ADMIN_BOARDCASE_MESSAGE = 53
    ADMIN_BOARDCASE_PHOTO = 54
    ADMIN_SEND = 55
